name: Publish to Dockerhub

on:
  workflow_dispatch:
    inputs:
      imagetype:
        description: "Build which image?"
        required: false
        default: "cpu"
        type: choice
        options:
          - "cpu"
          - "gpu"
      cachemodel:
        description: "Include a model into image?"
        required: false
        default: "small"
        type: choice
        options:
          - "tiny"
          - "tiny.en"
          - "base"
          - "base.en"
          - "small"
          - "small.en"
          - "medium"
          - "medium.en"
          - "large"
          - "all"
          - "all.en"
      tag:
        description: "Specify a custom tag?"
        required: false
        default: "latest"
        type: string

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub / GitHub Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Change repo name to lowercase
        run: |
          echo "REPO_LOWERCASE=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          echo "REPOTITLE_LOWERCASE=$(basename ${GITHUB_REPOSITORY,,})" >> ${GITHUB_ENV}

      - name: Set correct Dockerfile
        uses: haya14busa/action-cond@v1
        id: dockerfilechooser
        with:
          cond: ${{ inputs.imagetype == 'cpu' }}
          if_true: "Dockerfile"
          if_false: "Dockerfile.gpu"

      - name: Report
        run: echo "Building image from ${{ steps.dockerfilechooser.outputs.value }} and including ${{ inputs.cachemodel }} "

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push container image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOTITLE_LOWERCASE }}-${{ inputs.imagetype }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOTITLE_LOWERCASE }}-${{ inputs.imagetype }}:${{ inputs.cachemodel }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOTITLE_LOWERCASE }}-${{ inputs.imagetype }}:${{ inputs.tag }}
            ghcr.io/${{ env.REPO_LOWERCASE }}-${{ inputs.imagetype }}:${{ inputs.cachemodel }}
            ghcr.io/${{ env.REPO_LOWERCASE }}-${{ inputs.imagetype }}:${{ github.sha }}
            ghcr.io/${{ env.REPO_LOWERCASE }}-${{ inputs.imagetype }}:${{ inputs.tag }}
          build-args: |
            WHISPER_MODEL=${{ inputs.cachemodel }}
          file: ${{ steps.dockerfilechooser.outputs.value }}
